import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Runtime caching for unpkg
registerRoute(
    /^https:\/\/unpkg\.com\/.*/i,
    new CacheFirst({
        cacheName: 'unpkg-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 365 days
            }),
        ],
    })
);

// Handle Web Share Target
self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);
    if (event.request.method === 'POST' && url.pathname === '/_share-target') {
        event.respondWith((async () => {
            try {
                const formData = await event.request.formData();
                const file = formData.get('file');
                
                if (file) {
                    await new Promise((resolve, reject) => {
                        const request = indexedDB.open('nutriagenda-share', 1);
                        request.onupgradeneeded = (e) => {
                            e.target.result.createObjectStore('files');
                        };
                        request.onsuccess = (e) => {
                            const db = e.target.result;
                            const tx = db.transaction('files', 'readwrite');
                            tx.objectStore('files').put(file, 'shared-file');
                            tx.oncomplete = () => resolve();
                            tx.onerror = () => reject(tx.error);
                        };
                        request.onerror = () => reject(request.error);
                    });
                }
                
                // Redirect the user to the app's root to process the file
                return Response.redirect('/?action=share_received', 303);
            } catch (err) {
                console.error('[SW] Error handling share target:', err);
                return Response.redirect('/?action=share_error', 303);
            }
        })());
    }
});

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
